// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: icacontrol/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryButlers struct {
}

func (m *QueryButlers) Reset()         { *m = QueryButlers{} }
func (m *QueryButlers) String() string { return proto.CompactTextString(m) }
func (*QueryButlers) ProtoMessage()    {}
func (*QueryButlers) Descriptor() ([]byte, []int) {
	return fileDescriptor_e372f009937cf1e8, []int{0}
}
func (m *QueryButlers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryButlers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryButlers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryButlers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryButlers.Merge(m, src)
}
func (m *QueryButlers) XXX_Size() int {
	return m.Size()
}
func (m *QueryButlers) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryButlers.DiscardUnknown(m)
}

var xxx_messageInfo_QueryButlers proto.InternalMessageInfo

type QueryButlersResponse struct {
	Count   string   `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	Butlers []Butler `protobuf:"bytes,2,rep,name=butlers,proto3" json:"butlers"`
}

func (m *QueryButlersResponse) Reset()         { *m = QueryButlersResponse{} }
func (m *QueryButlersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryButlersResponse) ProtoMessage()    {}
func (*QueryButlersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e372f009937cf1e8, []int{1}
}
func (m *QueryButlersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryButlersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryButlersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryButlersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryButlersResponse.Merge(m, src)
}
func (m *QueryButlersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryButlersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryButlersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryButlersResponse proto.InternalMessageInfo

func (m *QueryButlersResponse) GetCount() string {
	if m != nil {
		return m.Count
	}
	return ""
}

func (m *QueryButlersResponse) GetButlers() []Butler {
	if m != nil {
		return m.Butlers
	}
	return nil
}

type QueryButler struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryButler) Reset()         { *m = QueryButler{} }
func (m *QueryButler) String() string { return proto.CompactTextString(m) }
func (*QueryButler) ProtoMessage()    {}
func (*QueryButler) Descriptor() ([]byte, []int) {
	return fileDescriptor_e372f009937cf1e8, []int{2}
}
func (m *QueryButler) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryButler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryButler.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryButler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryButler.Merge(m, src)
}
func (m *QueryButler) XXX_Size() int {
	return m.Size()
}
func (m *QueryButler) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryButler.DiscardUnknown(m)
}

var xxx_messageInfo_QueryButler proto.InternalMessageInfo

func (m *QueryButler) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryButlerResponse struct {
	Butler Butler `protobuf:"bytes,1,opt,name=butler,proto3" json:"butler"`
}

func (m *QueryButlerResponse) Reset()         { *m = QueryButlerResponse{} }
func (m *QueryButlerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryButlerResponse) ProtoMessage()    {}
func (*QueryButlerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e372f009937cf1e8, []int{3}
}
func (m *QueryButlerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryButlerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryButlerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryButlerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryButlerResponse.Merge(m, src)
}
func (m *QueryButlerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryButlerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryButlerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryButlerResponse proto.InternalMessageInfo

func (m *QueryButlerResponse) GetButler() Butler {
	if m != nil {
		return m.Butler
	}
	return Butler{}
}

func init() {
	proto.RegisterType((*QueryButlers)(nil), "icacontrol.v1.QueryButlers")
	proto.RegisterType((*QueryButlersResponse)(nil), "icacontrol.v1.QueryButlersResponse")
	proto.RegisterType((*QueryButler)(nil), "icacontrol.v1.QueryButler")
	proto.RegisterType((*QueryButlerResponse)(nil), "icacontrol.v1.QueryButlerResponse")
}

func init() { proto.RegisterFile("icacontrol/v1/query.proto", fileDescriptor_e372f009937cf1e8) }

var fileDescriptor_e372f009937cf1e8 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x8a, 0xd3, 0x40,
	0x18, 0x4f, 0xe2, 0xb6, 0x8b, 0xb3, 0xba, 0x87, 0xb1, 0xe2, 0x6e, 0x56, 0xb3, 0x6b, 0x16, 0x71,
	0x51, 0xcc, 0x90, 0x16, 0x8f, 0x5e, 0x7a, 0xf4, 0x66, 0x2e, 0x82, 0xb7, 0xc9, 0x74, 0x9c, 0x0e,
	0x34, 0xf3, 0xc5, 0xcc, 0xa4, 0x58, 0x44, 0x10, 0x9f, 0x40, 0xf0, 0x45, 0x7c, 0x8c, 0x1e, 0x0b,
	0x5e, 0x3c, 0x89, 0xb4, 0x82, 0x0f, 0xe1, 0x45, 0x92, 0x4c, 0x6b, 0x2a, 0xb4, 0xde, 0xbe, 0x2f,
	0xbf, 0xdf, 0xf7, 0xfb, 0x93, 0x04, 0x9d, 0x4a, 0x46, 0x19, 0x28, 0x53, 0xc0, 0x84, 0x4c, 0x63,
	0xf2, 0xa6, 0xe4, 0xc5, 0x2c, 0xca, 0x0b, 0x30, 0x80, 0x6f, 0xfe, 0x85, 0xa2, 0x69, 0xec, 0x9f,
	0x6d, 0x33, 0x05, 0x57, 0x5c, 0x4b, 0xdd, 0x70, 0xfd, 0x80, 0x81, 0xce, 0x40, 0x93, 0x94, 0x6a,
	0x4e, 0xa6, 0x71, 0xca, 0x0d, 0x8d, 0x09, 0x03, 0xa9, 0x2c, 0x7e, 0x57, 0x00, 0x88, 0x09, 0x27,
	0x34, 0x97, 0x84, 0x2a, 0x05, 0x86, 0x1a, 0x09, 0x6a, 0x7d, 0xdd, 0x13, 0x20, 0xa0, 0x1e, 0x49,
	0x35, 0xd9, 0xa7, 0xa7, 0xf6, 0xa6, 0xde, 0xd2, 0xf2, 0x35, 0xa1, 0xca, 0x46, 0xf3, 0xef, 0x58,
	0xbb, 0x4c, 0x8b, 0x2a, 0x4b, 0xa6, 0x45, 0x03, 0x84, 0xc7, 0xe8, 0xc6, 0x8b, 0xaa, 0xc2, 0xb0,
	0x34, 0x13, 0x5e, 0xe8, 0x90, 0xa1, 0x5e, 0x7b, 0x4f, 0xb8, 0xce, 0x41, 0x69, 0x8e, 0x7b, 0xa8,
	0xc3, 0xa0, 0x54, 0xe6, 0xc4, 0xbd, 0x70, 0xaf, 0xae, 0x27, 0xcd, 0x82, 0x9f, 0xa2, 0xc3, 0xb4,
	0x21, 0x9e, 0x78, 0x17, 0xd7, 0xae, 0x8e, 0xfa, 0xb7, 0xa3, 0xad, 0x77, 0x10, 0x35, 0x32, 0xc3,
	0x83, 0xf9, 0xf7, 0x73, 0x27, 0x59, 0x73, 0xc3, 0x7b, 0xe8, 0xa8, 0x65, 0x82, 0x8f, 0x91, 0x27,
	0x47, 0xb5, 0xf0, 0x41, 0xe2, 0xc9, 0x51, 0xf8, 0x1c, 0xdd, 0x6a, 0xc1, 0x9b, 0x08, 0x03, 0xd4,
	0x6d, 0x04, 0x6a, 0xea, 0x7f, 0xbc, 0x2c, 0xb5, 0xff, 0xdb, 0x45, 0x9d, 0x5a, 0x0c, 0x1b, 0x74,
	0x68, 0x4b, 0xe1, 0xb3, 0x7f, 0x2e, 0xdb, 0x8d, 0xfd, 0xcb, 0x3d, 0xe0, 0x3a, 0x4b, 0xf8, 0xf0,
	0xe3, 0xd7, 0x9f, 0x9f, 0xbd, 0xfb, 0xf8, 0x9c, 0x64, 0x3c, 0xe3, 0x63, 0x5e, 0x00, 0xd9, 0xfe,
	0xda, 0xb6, 0x2a, 0x2e, 0x51, 0xd7, 0xb6, 0xf4, 0x77, 0xeb, 0xfa, 0xe1, 0x6e, 0x6c, 0x63, 0xf9,
	0xb8, 0xb6, 0x7c, 0x80, 0x2f, 0xf7, 0x5b, 0x92, 0x77, 0x72, 0xf4, 0xde, 0xef, 0x7c, 0xf8, 0xf5,
	0xe5, 0x91, 0x3b, 0x7c, 0x39, 0x5f, 0x06, 0xee, 0x62, 0x19, 0xb8, 0x3f, 0x96, 0x81, 0xfb, 0x69,
	0x15, 0x38, 0x8b, 0x55, 0xe0, 0x7c, 0x5b, 0x05, 0xce, 0xab, 0x67, 0x42, 0x9a, 0x71, 0x99, 0x46,
	0x0c, 0xb2, 0x96, 0x9e, 0x32, 0xbc, 0x60, 0x63, 0x2a, 0xd5, 0x13, 0xcd, 0x59, 0x59, 0x48, 0x33,
	0xab, 0x84, 0xdf, 0xb6, 0x8d, 0xcc, 0x2c, 0xe7, 0x3a, 0xed, 0xd6, 0x7f, 0xcf, 0xe0, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0x51, 0x47, 0xa8, 0x0e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Butlers(ctx context.Context, in *QueryButlers, opts ...grpc.CallOption) (*QueryButlersResponse, error)
	Butler(ctx context.Context, in *QueryButler, opts ...grpc.CallOption) (*QueryButlerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Butlers(ctx context.Context, in *QueryButlers, opts ...grpc.CallOption) (*QueryButlersResponse, error) {
	out := new(QueryButlersResponse)
	err := c.cc.Invoke(ctx, "/icacontrol.v1.Query/Butlers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Butler(ctx context.Context, in *QueryButler, opts ...grpc.CallOption) (*QueryButlerResponse, error) {
	out := new(QueryButlerResponse)
	err := c.cc.Invoke(ctx, "/icacontrol.v1.Query/Butler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Butlers(context.Context, *QueryButlers) (*QueryButlersResponse, error)
	Butler(context.Context, *QueryButler) (*QueryButlerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Butlers(ctx context.Context, req *QueryButlers) (*QueryButlersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Butlers not implemented")
}
func (*UnimplementedQueryServer) Butler(ctx context.Context, req *QueryButler) (*QueryButlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Butler not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Butlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryButlers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Butlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/icacontrol.v1.Query/Butlers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Butlers(ctx, req.(*QueryButlers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Butler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryButler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Butler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/icacontrol.v1.Query/Butler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Butler(ctx, req.(*QueryButler))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "icacontrol.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Butlers",
			Handler:    _Query_Butlers_Handler,
		},
		{
			MethodName: "Butler",
			Handler:    _Query_Butler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "icacontrol/v1/query.proto",
}

func (m *QueryButlers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryButlers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryButlers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryButlersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryButlersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryButlersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Butlers) > 0 {
		for iNdEx := len(m.Butlers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Butlers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Count) > 0 {
		i -= len(m.Count)
		copy(dAtA[i:], m.Count)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Count)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryButler) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryButler) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryButler) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryButlerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryButlerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryButlerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Butler.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryButlers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryButlersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Count)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Butlers) > 0 {
		for _, e := range m.Butlers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryButler) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryButlerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Butler.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryButlers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryButlers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryButlers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryButlersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryButlersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryButlersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Count = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Butlers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Butlers = append(m.Butlers, Butler{})
			if err := m.Butlers[len(m.Butlers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryButler) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryButler: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryButler: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryButlerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryButlerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryButlerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Butler", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Butler.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
